# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller
    - gripper_trajectory_controller

  joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - robot_arm_shoulder_pan_joint
      - robot_arm_shoulder_lift_joint
      - robot_arm_elbow_joint
      - robot_arm_wrist_1_joint
      - robot_arm_wrist_2_joint
      - robot_arm_wrist_3_joint
    action_ns: follow_joint_trajectory
    default: true
  gripper_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - robotiq_85_left_inner_knuckle_joint
      - robotiq_85_left_knuckle_joint
      - robotiq_85_left_finger_tip_joint
      - robotiq_85_right_inner_knuckle_joint
      - robotiq_85_right_knuckle_joint
      - robotiq_85_right_finger_tip_joint
    action_ns: follow_joint_trajectory
    default: true