# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - robot_arm_shoulder_pan_joint
      - robot_arm_shoulder_lift_joint
      - robot_arm_elbow_joint
      - robot_arm_wrist_1_joint
      - robot_arm_wrist_2_joint
      - robot_arm_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
gripper_trajectory_controller:
  ros__parameters:
    joints:
      - robotiq_85_left_inner_knuckle_joint
      - robotiq_85_left_knuckle_joint
      - robotiq_85_left_finger_tip_joint
      - robotiq_85_right_inner_knuckle_joint
      - robotiq_85_right_knuckle_joint
      - robotiq_85_right_finger_tip_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    